version: "3.8"
services:
    drone:
        image: "drone/drone:1"
        container_name: "drone"
        env_file:
            - ".env"
        ports: 
            -   "127.0.0.1:9000:80"
        restart: "always"
        volumes:
            - /var/lib/drone:/data
    runner:
        image: "drone/drone-runner-docker:1"
        container_name: "docker-runner"
        env_file:
            - ".env"  
        expose: 
            - "3000"
        restart: "always"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        