version: "3.8"
services:
    drone:
        image: "drone/drone:1"
        container_name: "drone"
        env_file:
            - ".env"
        environment:
            DRONE_SERVER_PROTO: "http"
        ports: 
            -   target: "80"
                published: "127.0.0.1:9000"
                protocol: tcp
                mode: host
        restart: "always"
        volumes:
            - /var/lib/drone:/data
    runner:
        image: "drone/drone-runner-docker:1"
        container_name: "docker-runner"
        env_file:
            - ".env"
        environment:
            DRONE_RPC_PROTO: "http"
            DRONE_RPC_HOST: "drone"
            DRONE_RUNNER_CAPACITY: "2"
            DRONE_RUNNER_NAME: "docker-runner"
        expose: 
            - "3000"
        restart: "always"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        